// AUTH

export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = 'LOGOUT';

// REGIONS

export const FETCH_REGIONS = 'FETCH_REGIONS';

// POKEMONS

export const FETCH_POKEMONS = 'FETCH_POKEMONS';
export const FETCH_POKEMONS_START = 'FETCH_POKEMONS_START';
export const FETCH_POKEMONS_FINISH = 'FETCH_POKEMONS_FINISH';
